// Code generated by beauty; DO NOT EDIT.

package router

import (
	"net/http"
)

func routes() []Route {
	return []Route{
		{
			Method: "GET",
			URI: "/",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				w.Write([]byte("Hi"))
			},
		},
	}
}