// Code generated by beauty; DO NOT EDIT.

package router

import (
	"net/http"
)

var routes = []Route{
	{
		Method: "GET",
		URI: "/",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("Hi"))
		},
	},
}
