// Code generated by beauty; DO NOT EDIT.

package router

import (
	"net/http"
	"{{.ImportPath}}internal/endpoint/handlers"
)

// routes 定义所有路由
func routes() []Route {
	return []Route{
		{
			Method:  "GET",
			URI:     "/",
			Handler: handlers.Home,
			Name:    "home",
		},
		{
			Method:  "GET",
			URI:     "/ping",
			Handler: handlers.Ping,
			Name:    "ping",
		},
		// 在这里添加更多路由...
	}
}