// Code generated by beauty; DO NOT EDIT.

package router

import (
	"net/http"

	"github.com/rushteam/beauty"
)


var Routes = []beauty.Route{
	{
		URI: "/",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			w.Write([]byte("Welcome"))
		},
	},
}