// Code generated by beauty; DO NOT EDIT.

package router

import (
	"log"

	"github.com/gin-gonic/gin"
	"github.com/rushteam/beauty"
	"github.com/rushteam/beauty/pkg/service/web"
	"{{.ModPath}}internal/handler"
)

//App ..
func App() beauty.Service {
	srv, err := web.Build("app")
	if err != nil {
		log.Fatalln(err)
	}
	srv.GET("/", func(ctx *gin.Context) {
		// panic("test")
		ctx.String(200, "You're Beautiful!")
	})
	srv.GET("/v1/index", handler.Index)
	return srv
}
