// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
//
// 本目录由 `sqlc generate`(见 ../sqlc.yaml)从 ../schema.sql + ../query.sql 生成,
// 已提交以便示例自包含、无需先装 sqlc 即可编译运行。改了 SQL 后重跑 sqlc generate 覆盖。

package appdb

import (
	"context"
	"database/sql"
)

// DBTX 是查询执行接口。*sql.DB、*sql.Tx 均满足;beauty contrib/sqldb 的
// Writer()/Reader()/RW() 亦满足,可直接传给 New(...) 实现读写分离。
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}
