// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreateOrderInput struct {
	UserID string   `json:"userId"`
	Items  []string `json:"items"`
	Total  float64  `json:"total"`
}

type Mutation struct {
}

type Order struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userId"`
	Total     float64  `json:"total"`
	Status    string   `json:"status"`
	Items     []string `json:"items"`
	UpdatedAt string   `json:"updatedAt"`
	User      *User    `json:"user,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Orders []*Order `json:"orders"`
}
