package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	gqlauth "github.com/rushteam/beauty/contrib/graphql/auth"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input CreateOrderInput) (*Order, error) {
	if user, ok := gqlauth.GetUser(ctx); ok {
		slog.Info("createOrder by", "user_id", user.ID, "username", user.Username)
	}
	// 下游透传示例: meta 可注入 gRPC metadata / HTTP header
	_ = gqlauth.OutgoingMetadata(ctx)

	if r.Store.GetUser(input.UserID) == nil {
		return nil, fmt.Errorf("user %q not found", input.UserID)
	}
	return r.Store.CreateOrder(input), nil
}

// User is the resolver for the user field on Order (DataLoader).
func (r *orderResolver) User(ctx context.Context, obj *Order) (*User, error) {
	return loadUser(ctx, r.Store, obj.UserID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	return loadUser(ctx, r.Store, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int) ([]*User, error) {
	n := 10
	if limit != nil && *limit > 0 {
		n = *limit
	}
	return r.Store.ListUsers(n), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*Order, error) {
	return r.Store.GetOrder(id), nil
}

// OrderStatus is the resolver for the orderStatus field.
func (r *subscriptionResolver) OrderStatus(ctx context.Context, orderID string) (<-chan *Order, error) {
	if r.Store.GetOrder(orderID) == nil {
		return nil, fmt.Errorf("order %q not found", orderID)
	}
	ch := make(chan *Order, 1)
	go func() {
		defer close(ch)
		ticker := time.NewTicker(2 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				o := r.Store.AdvanceOrderStatus(orderID)
				if o == nil {
					return
				}
				select {
				case ch <- o:
				case <-ctx.Done():
					return
				}
				if o.Status == "delivered" {
					return
				}
			}
		}
	}()
	return ch, nil
}

// Orders is the resolver for the orders field.
func (r *userResolver) Orders(ctx context.Context, obj *User) ([]*Order, error) {
	return r.Store.OrdersByUserID(obj.ID), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
